# This file was generated by GoReleaser. DO NOT EDIT.
cask "govuk-cli" do
  version "0.0.4"

  on_macos do
    sha256 "be56aa710d6f257ad2d85a7bb03c4200f259660bccbedfede6f577f8eaa79c4f"
    url "https://github.com/alphagov/govuk-cli/releases/download/v#{version}/govuk-cli_Darwin_all.tar.gz"
  end

  name "govuk-cli"
  desc ""
  homepage "https://github.com/alphagov/govuk-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govuk-cli"
  bash_completion "completions/govuk-cli.bash"
  fish_completion "completions/govuk-cli.fish"
  zsh_completion "completions/govuk-cli.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govuk-cli"]
    end
  end

  # No zap stanza required

end
