# This file was generated by GoReleaser. DO NOT EDIT.
cask "govuk-cli" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "13b7397462f59681e7e67efac198e4c540faf6bfb0777761b6895703ed71b4d9"
      url "https://github.com/alphagov/govuk-cli/releases/download/v#{version}/govuk-cli_Darwin_x86_64"
      binary "govuk-cli_Darwin_x86_64", target: "govuk"
    end
    on_arm do
      sha256 "e029cd646e70f96a28218fe2bb0ddba7656cefb0914c24c0d713585f3f142add"
      url "https://github.com/alphagov/govuk-cli/releases/download/v#{version}/govuk-cli_Darwin_arm64"
      binary "govuk-cli_Darwin_arm64", target: "govuk"
    end
  end

  name "govuk-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  generate_completions_from_executable "govuk-cli", "completions",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
